server:
  port: 8081
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/zfenrir?characterEncoding=UTF8&amp&useSSL=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    hikari:
      auto-commit: true
      
      